---
# handlers file for ansible-role-docker-meilisearch
- name: Restart meilisearch
  systemd:
    name: docker-compose-service@meilisearch
    enabled: yes
    state: restarted
    daemon_reload: yes
